# MNIST
## 09. Activation Functions

In [1]:
from infdsa_mnist import mnist_load_normalized, mnist_output, activation_functions, activation_functions_output
import numpy as np

In the previous chapter, we have seen how to build a simple neural network. We let Keras handle the activation functions for us. In this chapter, we will zoom in on the activation functions and implement them ourselves.

In [2]:
(train_data, test_data) = mnist_load_normalized.load_mnist_flattened_normalized()
x_train, y_train = train_data
x_test, y_test = test_data

### Making pre-activation explicit

In [3]:
x = x_train[:10]

num_features = 784
num_neurons = 32

w = np.random.randn(num_features, num_neurons) * 0.01

b = np.zeros(num_neurons)

z = activation_functions.pre_activation(x, w, b)
print(z.shape)
print(z)

(10, 32)
[[ 3.43343835e-03 -6.52696439e-02  1.07392421e-02  1.54939138e-01
  -8.67566708e-02 -7.81414785e-02  3.47029962e-02  5.75625221e-02
   1.31329280e-02  4.12936589e-02 -3.34647300e-02 -1.92493515e-02
   5.24212713e-02 -1.33678895e-01  9.73805005e-02  3.56706627e-03
   6.41456609e-03 -2.69275122e-03  1.22917444e-01 -6.44319547e-02
   9.75051616e-02  7.52101924e-03 -2.53898328e-01  4.23965050e-02
   8.73978136e-02  4.42902107e-02  8.94720844e-02  2.98571096e-03
   1.79285806e-01 -3.26956238e-05 -8.01212407e-02 -5.25183287e-02]
 [-1.33862840e-01  1.06135337e-02  8.58857485e-03  1.23435977e-01
  -1.22046161e-01  7.42749639e-03 -1.18783889e-01 -4.84819013e-02
   6.87322177e-02 -6.16080623e-02  6.91053052e-02  8.57518460e-02
   1.11243694e-01 -1.21586912e-01  1.08958454e-01 -4.19539558e-02
   5.29068431e-02 -2.26601226e-02  3.80756677e-02 -1.14616363e-02
   6.10432467e-02  1.00765752e-01 -6.37005804e-02  1.25855137e-01
   2.31790100e-01  7.20890830e-02  4.52340086e-02  9.68931532e-02


The value of the pre-activation `z` receives the shape of (10, 32), which corresponds to the 10 samples in the batch and the 32 neurons in the layer. Each element in `z` represents the weighted sum of the input features for a particular neuron before applying the activation function. The values in `z` can be positive, negative, or zero, depending on the weights and inputs.

`z` is not yet the output of a neuron, as it has not been passed through an activation function. This is merely a step in the process to compute the output of the neurons. An activation function will be applied to `z` to let the network learn complex patterns in the data.

### ReLU

In [4]:
relu_int_neg = activation_functions.relu(-1)
print(relu_int_neg)

relu_int_nil = activation_functions.relu(0)
print(relu_int_nil)

relu_int_pos = activation_functions.relu(1)
print(relu_int_pos)

relu_arr = activation_functions.relu(z)
print(relu_arr)

0
0
1
[[0.00343344 0.         0.01073924 0.15493914 0.         0.
  0.034703   0.05756252 0.01313293 0.04129366 0.         0.
  0.05242127 0.         0.0973805  0.00356707 0.00641457 0.
  0.12291744 0.         0.09750516 0.00752102 0.         0.0423965
  0.08739781 0.04429021 0.08947208 0.00298571 0.17928581 0.
  0.         0.        ]
 [0.         0.01061353 0.00858857 0.12343598 0.         0.0074275
  0.         0.         0.06873222 0.         0.06910531 0.08575185
  0.11124369 0.         0.10895845 0.         0.05290684 0.
  0.03807567 0.         0.06104325 0.10076575 0.         0.12585514
  0.2317901  0.07208908 0.04523401 0.09689315 0.17592493 0.0583744
  0.         0.00711803]
 [0.         0.         0.03108662 0.         0.09044601 0.03686711
  0.         0.         0.09575549 0.         0.         0.
  0.0607269  0.07834785 0.0289215  0.02147369 0.02470464 0.09611492
  0.         0.09548856 0.08166791 0.09409847 0.         0.
  0.14316041 0.         0.12230789 0.02748227 0.   

### Sigmoid

In [5]:
sigmoid_int_neg = activation_functions.sigmoid(-1_000_000)
print(sigmoid_int_neg)

sigmoid_int_nil = activation_functions.sigmoid(0)
print(sigmoid_int_nil)

sigmoid_int_pos = activation_functions.sigmoid(1_000_000)
print(sigmoid_int_pos)

0.0
0.5
1.0


/Users/faye/Documents/GitHub/INFDSA_MNIST/infdsa_mnist/activation_functions.py:19: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


The sigmoid function ($\sigma(z) = \frac{1}{1 + e^{-z}}$) maps input values to a range between 0 and 1. For large negative inputs, the sigmoid function approaches 0, while for large positive inputs, it approaches 1. For an input of 0, the sigmoid function outputs 0.5, as an input of 0 makes sigmoid perfectly unsure whether the input is positive or negative. This behavior makes the sigmoid function useful for binary classification problems, where the output can be interpreted as a probability of belonging to a particular class.

As we can see from the outputs, `-1_000_000` and `1_000_000` are extremely large values for the sigmoid function. Euler's number `e` raised to the power of `-1_000_000` cannot be represented properly and results in an underflow, which is why we get 0 for the negative output. On the other hand, `e` raised to the power of `1_000_000` results in an overflow, which is why we get 1 for the positive output.

Let's show some "valid" values for the sigmoid function to see how it behaves in a more typical range.

In [6]:
sigmoid_int_neg = activation_functions.sigmoid(-9)
print(sigmoid_int_neg)

sigmoid_int_pos = activation_functions.sigmoid(9)
print(sigmoid_int_pos)

0.00012339457598623172
0.9998766054240137


These values are more typical for the sigmoid function. The negative and positive show the expected behavior of negative numbers being mapped close to 0 and positive numbers being mapped close to 1.

### Softmax

In [ ]:
z1 = [3.0, 1.0, 0.2]
z2 = [2.5, 4.9, 0.06]
z3 = [0.1, 0.2, 0.3]
z4 = [0.0, 0.0, 0.0]

softmax_z1 = activation_functions.softmax(z1)
print(softmax_z1)
print(np.sum(softmax_z1))

softmax_z2 = activation_functions.softmax(z2)
print(softmax_z2)
print(np.sum(softmax_z2))

softmax_z3 = activation_functions.softmax(z3)
print(softmax_z3)
print(np.sum(softmax_z3))

softmax_z4 = activation_functions.softmax(z4)
print(softmax_z4)
print(np.sum(softmax_z4))

[0.8360188  0.11314284 0.05083836]
0.9999999999999999
[0.08257408 0.91022869 0.00719723]
1.0
[0.30060961 0.33222499 0.3671654 ]
1.0000000000000002
[0.33333333 0.33333333 0.33333333]
1.0


The softmax function ($\sigma(z)_i = \frac{e^{z_i}}{\sum_{j=1}^{K} e^{z_j}}$) converts a vector of raw scores (called logits) into probabilities. The output of the softmax function is a probability distribution over the classes, where each value is between 0 and 1, and the sum of all values is equal to 1 (or very close to 1 due to floating-point precision limitations). In the examples provided, we can see that the softmax function has transformed the input vectors `z1`, `z2`, `z3`, and `z4` into probability distributions. The values in each output vector sum to 1, confirming that they represent valid probability distributions. The softmax function is commonly used in the output layer of neural networks for multi-class classification problems, where it helps to interpret the output as probabilities for each class. In a multi-class classification problem, the class with the highest probability can be selected as the predicted class for a given input.

### Neural Network with self-implemented activation functions

Before we can implement a neural network with self-implemented activation functions, let's create a simple neural network without activation functions to see what the output looks like. We will then add the activation functions to see how they affect the output.

In [8]:
model_raw = activation_functions.create_nn_no_activation(x_train.shape[1])
activation_functions.compile_nn(model_raw)
activation_functions.fit_nn(model_raw, x_train, y_train, epochs=2, batch_size=16, verbose=True)

Epoch 1/2
3375/3375 ━━━━━━━━━━━━━━━━━━━━ 3s 862us/step - accuracy: 0.5418 - loss: 1.9042 - val_accuracy: 0.5343 - val_loss: 1.4421
Epoch 2/2
3375/3375 ━━━━━━━━━━━━━━━━━━━━ 3s 793us/step - accuracy: 0.5116 - loss: 2.0281 - val_accuracy: 0.6060 - val_loss: 1.7170
Restoring model weights from the end of the best epoch: 1.


In [9]:
output = activation_functions_output.get_hidden_layer_output(model_raw, x_test)
print(output.shape)
print(output)

(10, 256)
[[-0.55113528  0.72114712  0.59244495 ... -1.02471897  1.2898138
  -0.83632739]
 [ 0.05496151  1.59723129 -1.10315295 ...  0.57161706  0.55026751
   0.11836125]
 [ 0.4739604   0.72687653 -0.36412921 ... -0.26034279 -0.53668579
   0.35045624]
 ...
 [-0.37081019 -0.90923095  0.57391971 ... -0.83274399  0.64362809
   0.5249795 ]
 [-0.18041983 -0.512715    0.70007949 ...  0.8623288   1.41442476
   1.19396227]
 [ 0.49546331  1.11210084 -0.32002108 ... -0.82285255  0.45436397
   0.82762466]]


The output of the hidden layer without activation functions is a linear transformation of the input data. The values can be positive, negative, or zero. In order for the neural network to learn complex patterns in the data, we need to introduce activation functions. Let's add our self-implemented activation functions to the hidden layer and see how the output changes. Do note that we will use slightly different activation functions than the ones we implemented earlier, as we used NumPy for earlier implementations, and Keras does not like us to use NumPy functions in the model. We will recreate the activation functions using Keras instead.

In [10]:
model = activation_functions.create_nn(x_train.shape[1])
activation_functions.compile_nn(model)
activation_functions.fit_nn(model, x_train, y_train, epochs=2, batch_size=16, verbose=True)

Epoch 1/2
3375/3375 ━━━━━━━━━━━━━━━━━━━━ 3s 823us/step - accuracy: 0.9030 - loss: 0.3225 - val_accuracy: 0.9707 - val_loss: 0.1025
Epoch 2/2
3375/3375 ━━━━━━━━━━━━━━━━━━━━ 3s 852us/step - accuracy: 0.9444 - loss: 0.1802 - val_accuracy: 0.9773 - val_loss: 0.0783
Restoring model weights from the end of the best epoch: 2.


In [11]:
output = activation_functions_output.get_hidden_layer_output(model, x_test)
print(output.shape)
print(output)

(10, 256)
[[0.         0.30158942 0.81609291 ... 0.018293   1.45675007 1.97861727]
 [0.42205751 1.58812441 1.11545826 ... 0.         1.30978808 0.        ]
 [0.         1.39860392 0.         ... 1.09831802 0.74521523 0.44208859]
 ...
 [1.06914183 0.28588959 0.         ... 0.         0.67401631 0.        ]
 [0.72562938 3.31586551 0.         ... 1.60566994 0.         0.        ]
 [0.33922111 2.7067168  0.         ... 0.         1.30774701 0.60750091]]


As we can see, the output of the hidden layer with activation functions no longer features negative values. The activation functions have introduced non-linearity to the model, allowing it to learn more complex patterns in the data. Do, however, note that the numbers printed are not entirely the same as the ones within the model itself. This is because the `get_hidden_layer_output` function does not take the Batch Normalization layer into account, which is present in the model. The Batch Normalization layer normalizes the output of the hidden layer, which can affect the values we see when we print the output. Since both models above do feature Batch Normalization, this should not pose a problem for our comparison. The main takeaway is that the activation functions have introduced the ability to learn complex patterns in the data, which is essential for performance.

### Output layer activation functions

To end off this chapter, let's take a look at the output layer activation functions. Typically, we would use the softmax activation function for multi-class classification problems, as it converts the raw output scores into probabilities. However, we can use other activation functions as well, such as sigmoid. Let's see how the output changes between using softmax and sigmoid in the output layer. Considering the model with activation functions already has a softmax activation function in the output layer, we will use the raw model without activation functions to test the effect of different output layer activation functions. Our aim with this exercise will not be to achieve good performance, but rather to see the effect of different activation functions on the output.

In [12]:
raw_model_output = model_raw.predict(x_test[:1])
print(f"Raw final layer output (Logits):\n {raw_model_output}")

raw_model_output_sigmoid = activation_functions.sigmoid(raw_model_output)
print(f"\nSigmoid output:\n {raw_model_output_sigmoid}")

raw_model_output_softmax = activation_functions.softmax(raw_model_output)
print(f"\nSoftmax output:\n {raw_model_output_softmax}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
Raw final layer output (Logits):
 [[-0.82938063 -1.3372698  -2.5299332   0.9842529  -2.2664523  -1.6770093
  -2.031776    2.0417967  -1.8098267  -1.442908  ]]

Sigmoid output:
 [[0.30377606 0.2079594  0.07378621 0.7279513  0.09393974 0.15749188
  0.11590681 0.8851161  0.14065906 0.19109541]]

Softmax output:
 [[0.03641934 0.02191586 0.00664954 0.22334853 0.00865406 0.01560313
  0.01094305 0.64308524 0.01366249 0.0197188 ]]


Let's go through these results.

The raw final layer output (logits) is a vector of raw scores for each class. These scores can be positive, negative, or zero, and they do not represent probabilities. However, we can tell by the values that the model is more confident in some classes than others, as some scores are higher than others. From this, we can make a guess about which class the model would predict, which would be the class with the highest score.

When we apply the sigmoid function to the raw output, we get values between zero and one for each class. However, sigmoid treats every value as a separate yes/no question, as opposed to treating all values as part of a whole. This means that the output does not represent a valid probability distribution, as the values do not sum to 1. It still gives us an idea of how confident the model is in each class, but it does not allow us to directly compare the classes against each other.

When we apply the softmax function to the raw output, we once again get values between zero and one for each class. In contrast to sigmoid, softmax treats the output as a whole and converts it into a valid probability distribution. The values sum to 1, which allows us to directly compare the classes against each other. The class with the highest probability is the one that the model would predict.

### Deploying to the Mystery Device

To ensure the neural network can be deployed to the Mystery Device, we must consider the 256 KB RAM and 1 MB storage constraints. The model we have built in this chapter is too large to fit within its constraints, so we would have to optimize the model further to reduce its size. The model we have used in this chapter is based on the one we built in the previous chapter. In the previous chapter, we have already optimized the model to fit within the RAM and storage constraints of the Mystery Device.

The biggest wins in optimizing the model for deployment come down to these steps:
- Use a smaller model architecture (fewer layers and neurons).
- ReLU activation functions in the hidden layers, as they are mathematically efficient.
- Remove the optimizer from the model, as it is useless for inference and takes up a lot of space.
- Use TensorFlow Lite to convert all 32-bit floating-point numbers to 8-bit integers.